import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '@mescius/wijmo.styles/wijmo.css';
import DefaultLayout from '@/components/Layouts/DefaultLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Airport dashboard',
  description: 'Generated by create next app and wijmo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DefaultLayout>{children}</DefaultLayout>
      </body>
    </html>
  );
}
